export const MONTH_NAMES = [
  "January", "February", "March", "April", "May", "June",
  "July", "August", "September", "October", "November", "December",
];

export const API_BASE = "https://api-google-maker.cloudflare-5e0.workers.dev";
export const API_TIMEOUT = 30000;
export const API_MAX_RETRIES = 3;
export const API_RETRY_BASE_MS = 1000;
export const SMS_POLL_INTERVAL = 3000;
export const SMS_TIMEOUT = 90000;
export const RECOVERY_POLL_INTERVAL = 3000;
export const RECOVERY_TIMEOUT = 90000;

export const DELAY = {
  TINY: [40, 100],
  SHORT: [300, 700],
  MEDIUM: [700, 1800],
  LONG: [1200, 3000],
  EXTRA_LONG: [2000, 5000],
  TYPING: [60, 180],
  TYPING_PAUSE: [400, 900],
  BACKSPACE: [100, 250],
};

export const STATE = {
  IDLE: "IDLE",
  SIGNING_IN: "SIGNING_IN",
  FILLING_NAME: "FILLING_NAME",
  FILLING_BIRTHDAY: "FILLING_BIRTHDAY",
  FILLING_USERNAME: "FILLING_USERNAME",
  FILLING_PASSWORD: "FILLING_PASSWORD",
  PHONE_VERIFICATION: "PHONE_VERIFICATION",
  WAITING_SMS: "WAITING_SMS",
  FILLING_RECOVERY: "FILLING_RECOVERY",
  SKIPPING_RECOVERY_PHONE: "SKIPPING_RECOVERY_PHONE",
  CONFIRMING: "CONFIRMING",
  ACCEPTING_TERMS: "ACCEPTING_TERMS",
  NAVIGATING_SECURITY: "NAVIGATING_SECURITY",
  NAVIGATING_RECOVERY_EMAIL: "NAVIGATING_RECOVERY_EMAIL",
  VERIFYING_RECOVERY_EMAIL: "VERIFYING_RECOVERY_EMAIL",
  SECURITY_CHALLENGE: "SECURITY_CHALLENGE",
  COMPLETED: "COMPLETED",
  ERROR: "ERROR",
};

export const TAG = "[GoogleAccounts]";
export const SESSION_KEY = "gah_config";
export const SETTINGS_KEY = "gah_settings";
